repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
#      - id: double-quote-string-fixer
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: ["--target-version", "py310"]
#  - repo: https://github.com/PyCQA/flake8
#    rev: 6.0.0
#    hooks:
#      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-setuptools
          - types-six
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.4
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest # Command to run
        language: system # Assumes pytest is installed in the environment
        types: [python] # Run only when Python files change
        pass_filenames: false # Run pytest on the whole project, not just changed files
        always_run: false
        stages:
          - "push"
